// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filterInput': string;
  'modalBody': string;
  'scroller': string;
}
export const cssExports: CssExports;
export default cssExports;
