// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'imdbId': string;
  'title': string;
  'tvdbId': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
