// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'debug': string;
  'error': string;
  'fatal': string;
  'info': string;
  'level': string;
  'trace': string;
  'warn': string;
}
export const cssExports: CssExports;
export default cssExports;
