// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'leftButtons': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
