// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enable': string;
  'implementation': string;
  'name': string;
  'priority': string;
  'removeCompletedDownloads': string;
  'removeFailedDownloads': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
