// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'example': string;
  'insert': string;
  'isFullFilename': string;
  'large': string;
  'lower': string;
  'note': string;
  'noteBody': string;
  'option': string;
  'small': string;
  'title': string;
  'token': string;
  'upper': string;
}
export const cssExports: CssExports;
export default cssExports;
