// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'builder': string;
  'control': string;
  'controlLabel': string;
  'controls': string;
  'footNote': string;
  'formatInput': string;
  'groups': string;
  'identifier': string;
  'instruction': string;
  'namingSelect': string;
  'noResults': string;
  'preview': string;
  'previewInvalid': string;
  'previewLabel': string;
  'previewValue': string;
  'search': string;
}
export const cssExports: CssExports;
export default cssExports;
