// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footNote': string;
  'groups': string;
  'icon': string;
  'namingSelect': string;
  'namingSelectContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
