// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkContainer': string;
  'icon': string;
  'selected': string;
  'unselected': string;
}
export const cssExports: CssExports;
export default cssExports;
