// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allEpisodes': string;
  'episodes': string;
  'info': string;
  'season': string;
}
export const cssExports: CssExports;
export default cssExports;
