// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customFormat': string;
  'iconButton': string;
  'name': string;
  'nameContainer': string;
  'overlay': string;
  'rightCluster': string;
  'statusDot': string;
  'statusDotMuted': string;
  'statusLine': string;
}
export const cssExports: CssExports;
export default cssExports;
