// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCustomFormat': string;
  'center': string;
  'customFormats': string;
}
export const cssExports: CssExports;
export default cssExports;
