// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addLabel': string;
  'addSpecification': string;
  'center': string;
  'conditions': string;
  'conditionsTitle': string;
  'customFormats': string;
  'fullWidth': string;
  'intro': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
