// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addSpecification': string;
  'center': string;
  'customFormats': string;
  'deleteButton': string;
  'rightButtons': string;
}
export const cssExports: CssExports;
export default cssExports;
