// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldSection': string;
  'labels': string;
  'metadata': string;
  'name': string;
  'overlay': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
