// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasError': string;
  'hasWarning': string;
  'input': string;
  'inputContainer': string;
  'suggestion': string;
  'suggestionHighlighted': string;
  'suggestionsContainer': string;
  'suggestionsContainerOpen': string;
  'suggestionsList': string;
}
export const cssExports: CssExports;
export default cssExports;
