// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'captchaInputWrapper': string;
  'hasButton': string;
  'hasError': string;
  'hasWarning': string;
  'input': string;
  'recaptchaWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
