// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'container': string;
  'dangerIsChecked': string;
  'helpText': string;
  'input': string;
  'isDisabled': string;
  'isIndeterminate': string;
  'isNotChecked': string;
  'label': string;
  'primaryIsChecked': string;
  'successIsChecked': string;
  'warningIsChecked': string;
}
export const cssExports: CssExports;
export default cssExports;
