// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'container': string;
  'danger': string;
  'helpText': string;
  'input': string;
  'isDisabled': string;
  'isIndeterminate': string;
  'isNotChecked': string;
  'label': string;
  'primary': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
