// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extraSmall': string;
  'large': string;
  'medium': string;
  'right': string;
  'row': string;
  'small': string;
  'stacked': string;
}
export const cssExports: CssExports;
export default cssExports;
