// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'helpText': string;
  'isCheckInput': string;
  'isError': string;
  'isWarning': string;
  'link': string;
}
export const cssExports: CssExports;
export default cssExports;
