// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasError': string;
  'isAdvanced': string;
  'label': string;
  'large': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
