// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'helpLink': string;
  'inputContainer': string;
  'inputGroup': string;
  'inputGroupContainer': string;
  'inputUnit': string;
  'inputUnitNumber': string;
  'pendingChangesContainer': string;
  'pendingChangesIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
