// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hintText': string;
  'selectedValue': string;
  'valueText': string;
}
export const cssExports: CssExports;
export default cssExports;
