// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editButton': string;
  'editContainer': string;
  'label': string;
  'link': string;
  'linkWithEdit': string;
  'tag': string;
}
export const cssExports: CssExports;
export default cssExports;
