// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'hasError': string;
  'hasWarning': string;
  'input': string;
  'readOnly': string;
}
export const cssExports: CssExports;
export default cssExports;
