// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'inputFolder': string;
  'inputUnit': string;
  'inputUnitWrapper': string;
  'inputWrapper': string;
  'readOnly': string;
  'unit': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
