// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'customFormatScore': string;
  'progress': string;
  'protocol': string;
  'quality': string;
}
export const cssExports: CssExports;
export default cssExports;
