// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'existing': string;
  'title': string;
  'titleContainer': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
