// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'content': string;
  'contentContainer': string;
  'dropdownArrowContainer': string;
  'existing': string;
  'loading': string;
  'results': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'warningIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
