// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'series': string;
  'tvdbLink': string;
  'tvdbLinkIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
