// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'field': string;
  'input': string;
  'loadingIndicator': string;
  'results': string;
  'searchIcon': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
