// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'additionalInfo': string;
  'step': string;
  'stepState': string;
  'steps': string;
}
export const cssExports: CssExports;
export default cssExports;
