// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'copyButton': string;
  'link': string;
  'linkBlock': string;
  'links': string;
}
export const cssExports: CssExports;
export default cssExports;
