// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'backdrop': string;
  'backdropOverlay': string;
  'contentContainer': string;
  'details': string;
  'detailsChips': string;
  'detailsLabel': string;
  'fileCountMessage': string;
  'genres': string;
  'header': string;
  'headerContent': string;
  'heartRating': string;
  'info': string;
  'innerContentBody': string;
  'links': string;
  'monitorToggleButton': string;
  'network': string;
  'originalCountry': string;
  'originalLanguageName': string;
  'overview': string;
  'overviewFrame': string;
  'overviewLabel': string;
  'overviewSection': string;
  'path': string;
  'poster': string;
  'qualityProfileName': string;
  'runtime': string;
  'seriesNavigationButton': string;
  'seriesNavigationButtons': string;
  'seriesProgressLabel': string;
  'sizeOnDisk': string;
  'statusName': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
