// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'backdrop': string;
  'backdropOverlay': string;
  'chipsRow': string;
  'contentContainer': string;
  'details': string;
  'detailsChips': string;
  'detailsLabel': string;
  'fileCountMessage': string;
  'genres': string;
  'header': string;
  'headerContent': string;
  'heartRating': string;
  'heroFooter': string;
  'info': string;
  'innerContentBody': string;
  'links': string;
  'monitoredText': string;
  'monitoredToggle': string;
  'network': string;
  'originalCountry': string;
  'originalLanguageName': string;
  'overview': string;
  'overviewClamped': string;
  'overviewFrame': string;
  'overviewLabel': string;
  'overviewSection': string;
  'overviewToggle': string;
  'pathLine': string;
  'poster': string;
  'qualityProfileName': string;
  'runtime': string;
  'seriesNavigationButton': string;
  'seriesNavigationButtons': string;
  'seriesProgressLabel': string;
  'sizeOnDisk': string;
  'statusName': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
