// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actions': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'collapseButtonContainer': string;
  'collapseButtonIcon': string;
  'episodeCountTooltip': string;
  'episodes': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'left': string;
  'noEpisodes': string;
  'season': string;
  'seasonNumber': string;
  'sizeOnDisk': string;
}
export const cssExports: CssExports;
export default cssExports;
