// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitle': string;
  'comment': string;
}
export const cssExports: CssExports;
export default cssExports;
