// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'episodeTitle': string;
  'header': string;
  'openSeriesButton': string;
  'scope': string;
  'scopeLine': string;
  'scopeSeparator': string;
  'scopeSeries': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
  'tabs': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
