// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'openSeriesButton': string;
  'selectedTab': string;
  'separator': string;
  'seriesTitle': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
