// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteEpisodeNumber': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
