// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'actions': string;
  'content': string;
  'continuing': string;
  'deleted': string;
  'ended': string;
  'info': string;
  'link': string;
  'poster': string;
  'posterContainer': string;
  'posterImage': string;
  'statusLabel': string;
  'statusPill': string;
  'synopsis': string;
  'title': string;
  'titleRow': string;
  'upcoming': string;
}
export const cssExports: CssExports;
export default cssExports;
