// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chip': string;
  'chipAiring': string;
  'chipPath': string;
  'chipStrip': string;
  'chipTag': string;
  'dateLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
