// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alert': string;
  'danger': string;
  'info': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
