// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'circularProgressBar': string;
  'circularProgressBarContainer': string;
  'circularProgressBarText': string;
}
export const cssExports: CssExports;
export default cssExports;
