// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fieldSet': string;
  'legend': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
