// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'danger': string;
  'default': string;
  'disabled': string;
  'info': string;
  'inverse': string;
  'label': string;
  'large': string;
  'medium': string;
  'outline': string;
  'primary': string;
  'small': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
