// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isDisabled': string;
  'toggleButton': string;
}
export const cssExports: CssExports;
export default cssExports;
