// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backText': string;
  'backTextContainer': string;
  'container': string;
  'danger': string;
  'frontText': string;
  'frontTextContainer': string;
  'info': string;
  'large': string;
  'medium': string;
  'primary': string;
  'progressBar': string;
  'purple': string;
  'small': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
