// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'description': string;
  'descriptionList': string;
  'levelMapped': string;
  'levelMixed': string;
  'levelNone': string;
  'levelNormal': string;
  'levelNotRequested': string;
  'levelUnknown': string;
  'messages': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
