// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'group': string;
  'groupHeading': string;
  'lists': string;
}
export const cssExports: CssExports;
export default cssExports;
