// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addLabel': string;
  'addList': string;
  'center': string;
  'lists': string;
}
export const cssExports: CssExports;
export default cssExports;
