// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  externalDecision: string;
  name: string;
  overlay: string;
  underlay: string;
}
export const cssExports: CssExports;
export default cssExports;
