// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  externalDecision: string;
  name: string;
}
export const cssExports: CssExports;
export default cssExports;
