// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  addExternalDecision: string;
  center: string;
  externalDecisions: string;
}
export const cssExports: CssExports;
export default cssExports;
