// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'meta': string;
  'metaItem': string;
  'metaLabel': string;
  'metaValue': string;
  'overview': string;
}
export const cssExports: CssExports;
export default cssExports;
