// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'fileRow': string;
  'files': string;
  'filesHeader': string;
  'infoTitle': string;
  'overview': string;
  'path': string;
  'quality': string;
  'size': string;
}
export const cssExports: CssExports;
export default cssExports;
