// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNotificationTemplate': string;
  'center': string;
  'notificationTemplates': string;
}
export const cssExports: CssExports;
export default cssExports;
