// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'interval': string;
  'lastDuration': string;
  'lastExecution': string;
  'nextExecution': string;
}
export const cssExports: CssExports;
export default cssExports;
