// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message': string;
  'renameIcon': string;
  'result': string;
}
export const cssExports: CssExports;
export default cssExports;
