// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'customFormatScore': string;
  'details': string;
  'downloadClient': string;
  'indexer': string;
  'releaseGroup': string;
}
export const cssExports: CssExports;
export default cssExports;
