// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'loading': string;
  'navButton': string;
  'navigationButtons': string;
  'titleDesktop': string;
  'titleMobile': string;
  'todayButton': string;
  'viewButton': string;
  'viewButtonsContainer': string;
  'viewMenu': string;
}
export const cssExports: CssExports;
export default cssExports;
