// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'loading': string;
  'navigationButtons': string;
  'title': string;
  'todayButton': string;
  'viewButtonsContainer': string;
  'viewMenu': string;
}
export const cssExports: CssExports;
export default cssExports;
