// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'indicatorContainer': string;
  'label': string;
  'labelContainer': string;
  'menuButton': string;
}
export const cssExports: CssExports;
export default cssExports;
