<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common.Test\Sonarr.Common.Test.csproj" />
    <ProjectReference Include="..\NzbDrone.Mono\Sonarr.Mono.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Sonarr.Test.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Files\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
