// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addErrorAlert': string;
  'code': string;
  'header': string;
  'importButtonIcon': string;
  'recentFolders': string;
  'startImport': string;
  'tip': string;
  'tips': string;
}
export const cssExports: CssExports;
export default cssExports;
