// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addErrorAlert': string;
  'chooseFolderButtonContainer': string;
  'importButtonIcon': string;
  'tips': string;
  'tipsChevron': string;
  'tipsList': string;
  'tipsSummary': string;
}
export const cssExports: CssExports;
export default cssExports;
