// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'empty': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
