// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteCount': string;
  'deleteFilesMessage': string;
  'folderPath': string;
  'pathContainer': string;
  'pathIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
