// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'indexer': string;
  'name': string;
  'overlay': string;
  'presetsMenu': string;
  'presetsMenuButton': string;
  'underlay': string;
}
export const cssExports: CssExports;
export default cssExports;
