// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'failures': string;
  'results': string;
}
export const cssExports: CssExports;
export default cssExports;
