//
// Regular

import farBookmark from '@fortawesome/fontawesome-free-regular/faBookmark';
import farCalendar from '@fortawesome/fontawesome-free-regular/faCalendar';
import farCircle from '@fortawesome/fontawesome-free-regular/faCircle';
import farClock from '@fortawesome/fontawesome-free-regular/faClock';
import farClone from '@fortawesome/fontawesome-free-regular/faClone';
import farDotCircle from '@fortawesome/fontawesome-free-regular/faDotCircle';
import farFile from '@fortawesome/fontawesome-free-regular/faFile';
import farFileArchive from '@fortawesome/fontawesome-free-regular/faFileArchive';
import farFileVideo from '@fortawesome/fontawesome-free-regular/faFileVideo';
import farFolder from '@fortawesome/fontawesome-free-regular/faFolder';
import farObjectGroup from '@fortawesome/fontawesome-free-regular/faObjectGroup';
import farHdd from '@fortawesome/fontawesome-free-regular/faHdd';
import farKeyboard from '@fortawesome/fontawesome-free-regular/faKeyboard';
import farObjectUngroup from '@fortawesome/fontawesome-free-regular/faObjectUngroup';

//
// Solid

import fasArrowCircleLeft from '@fortawesome/fontawesome-free-solid/faArrowCircleLeft';
import fasArrowCircleRight from '@fortawesome/fontawesome-free-solid/faArrowCircleRight';
import fasBackward from '@fortawesome/fontawesome-free-solid/faBackward';
import fasBars from '@fortawesome/fontawesome-free-solid/faBars';
import fasBolt from '@fortawesome/fontawesome-free-solid/faBolt';
import fasBookmark from '@fortawesome/fontawesome-free-solid/faBookmark';
import fasBug from '@fortawesome/fontawesome-free-solid/faBug';
import fasCalendarAlt from '@fortawesome/fontawesome-free-solid/faCalendarAlt';
import fasCaretDown from '@fortawesome/fontawesome-free-solid/faCaretDown';
import fasCheck from '@fortawesome/fontawesome-free-solid/faCheck';
import fasChevronCircleDown from '@fortawesome/fontawesome-free-solid/faChevronCircleDown';
import fasChevronCircleRight from '@fortawesome/fontawesome-free-solid/faChevronCircleRight';
import fasChevronCircleUp from '@fortawesome/fontawesome-free-solid/faChevronCircleUp';
import fasCheckCircle from '@fortawesome/fontawesome-free-solid/faCheckCircle';
import fasCircle from '@fortawesome/fontawesome-free-solid/faCircle';
import fasCloudDownloadAlt from '@fortawesome/fontawesome-free-solid/faCloudDownloadAlt';
import fasCloud from '@fortawesome/fontawesome-free-solid/faCloud';
import fasCog from '@fortawesome/fontawesome-free-solid/faCog';
import fasCogs from '@fortawesome/fontawesome-free-solid/faCogs';
import fasCopy from '@fortawesome/fontawesome-free-solid/faCopy';
import fasDesktop from '@fortawesome/fontawesome-free-solid/faDesktop';
import fasDownload from '@fortawesome/fontawesome-free-solid/faDownload';
import fasEllipsisH from '@fortawesome/fontawesome-free-solid/faEllipsisH';
import fasExclamationCircle from '@fortawesome/fontawesome-free-solid/faExclamationCircle';
import fasExclamationTriangle from '@fortawesome/fontawesome-free-solid/faExclamationTriangle';
import fasExternalLinkAlt from '@fortawesome/fontawesome-free-solid/faExternalLinkAlt';
import fasEye from '@fortawesome/fontawesome-free-solid/faEye';
import fasFastBackward from '@fortawesome/fontawesome-free-solid/faFastBackward';
import fasFastForward from '@fortawesome/fontawesome-free-solid/faFastForward';
import fasFilter from '@fortawesome/fontawesome-free-solid/faFilter';
import fasFolderOpen from '@fortawesome/fontawesome-free-solid/faFolderOpen';
import fasForward from '@fortawesome/fontawesome-free-solid/faForward';
import fasHeart from '@fortawesome/fontawesome-free-solid/faHeart';
import fasHistory from '@fortawesome/fontawesome-free-solid/faHistory';
import fasHome from '@fortawesome/fontawesome-free-solid/faHome';
import fasInfoCircle from '@fortawesome/fontawesome-free-solid/faInfoCircle';
import fasLaptop from '@fortawesome/fontawesome-free-solid/faLaptop';
import fasLevelUpAlt from '@fortawesome/fontawesome-free-solid/faLevelUpAlt';
import fasMedkit from '@fortawesome/fontawesome-free-solid/faMedkit';
import fasMinus from '@fortawesome/fontawesome-free-solid/faMinus';
import fasPause from '@fortawesome/fontawesome-free-solid/faPause';
import fasPlay from '@fortawesome/fontawesome-free-solid/faPlay';
import fasPlus from '@fortawesome/fontawesome-free-solid/faPlus';
import fasPowerOff from '@fortawesome/fontawesome-free-solid/faPowerOff';
import fasQuestion from '@fortawesome/fontawesome-free-solid/faQuestion';
import fasQuestionCircle from '@fortawesome/fontawesome-free-solid/faQuestionCircle';
import fasRedoAlt from '@fortawesome/fontawesome-free-solid/faRedoAlt';
import fasRetweet from '@fortawesome/fontawesome-free-solid/faRetweet';
import fasRss from '@fortawesome/fontawesome-free-solid/faRss';
import fasRocket from '@fortawesome/fontawesome-free-solid/faRocket';
import fasSave from '@fortawesome/fontawesome-free-solid/faSave';
import fasSearch from '@fortawesome/fontawesome-free-solid/faSearch';
import fasSignal from '@fortawesome/fontawesome-free-solid/faSignal';
import fasSignoutAlt from '@fortawesome/fontawesome-free-solid/faSignOutAlt';
import fasSitemap from '@fortawesome/fontawesome-free-solid/faSitemap';
import fasSpinner from '@fortawesome/fontawesome-free-solid/faSpinner';
import fasSort from '@fortawesome/fontawesome-free-solid/faSort';
import fasSortDown from '@fortawesome/fontawesome-free-solid/faSortDown';
import fasSortUp from '@fortawesome/fontawesome-free-solid/faSortUp';
import fasStop from '@fortawesome/fontawesome-free-solid/faStop';
import fasSync from '@fortawesome/fontawesome-free-solid/faSync';
import fasTags from '@fortawesome/fontawesome-free-solid/faTags';
import fasTh from '@fortawesome/fontawesome-free-solid/faTh';
import fasThList from '@fortawesome/fontawesome-free-solid/faThList';
import fasTrashAlt from '@fortawesome/fontawesome-free-solid/faTrashAlt';
import fasTimes from '@fortawesome/fontawesome-free-solid/faTimes';
import fasTimesCircle from '@fortawesome/fontawesome-free-solid/faTimesCircle';
import fasUser from '@fortawesome/fontawesome-free-solid/faUser';
import fasWrench from '@fortawesome/fontawesome-free-solid/faWrench';

//
// Icons

export const ACTIONS = fasBolt;
export const ACTIVITY = farClock;
export const ADD = fasPlus;
export const ALTERNATE_TITLES = farClone;
export const ADVANCED_SETTINGS = fasCog;
export const ARROW_LEFT = fasArrowCircleLeft;
export const ARROW_RIGHT = fasArrowCircleRight;
export const BACKUP = farFileArchive;
export const BUG = fasBug;
export const CALENDAR = fasCalendarAlt;
export const CALENDAR_O = farCalendar;
export const CARET_DOWN = fasCaretDown;
export const CHECK = fasCheck;
export const CHECK_INDETERMINATE = fasMinus;
export const CHECK_CIRCLE = fasCheckCircle;
export const CIRCLE = fasCircle;
export const CIRCLE_OUTLINE = farCircle;
export const CLEAR = fasTrashAlt;
export const CLIPBOARD = fasCopy;
export const CLOSE = fasTimes;
export const CLONE = farClone;
export const COLLAPSE = fasChevronCircleUp;
export const COMPUTER = fasDesktop;
export const DANGER = fasExclamationCircle;
export const DELETE = fasTrashAlt;
export const DOWNLOAD = fasDownload;
export const DOWNLOADED = fasDownload;
export const DOWNLOADING = fasCloudDownloadAlt;
export const DRIVE = farHdd;
export const EDIT = fasWrench;
export const EPISODE_FILE = farFileVideo;
export const EXPAND = fasChevronCircleDown;
export const EXPAND_INDETERMINATE = fasChevronCircleRight;
export const EXTERNAL_LINK = fasExternalLinkAlt;
export const FATAL = fasTimesCircle;
export const FILE = farFile;
export const FILTER = fasFilter;
export const FOLDER = farFolder;
export const FOLDER_OPEN = fasFolderOpen;
export const GROUP = farObjectGroup;
export const HEALTH = fasMedkit;
export const HEART = fasHeart;
export const HISTORY = fasHistory;
export const HOUSEKEEPING = fasHome;
export const INFO = fasInfoCircle;
export const INTERACTIVE = fasUser;
export const KEYBOARD = farKeyboard;
export const LOGOUT = fasSignoutAlt;
export const MISSING = fasExclamationTriangle;
export const MONITORED = fasBookmark;
export const NETWORK = fasSignal;
export const NAVBAR_COLLAPSE = fasBars;
export const NOT_AIRED = farClock;
export const ORGANIZE = fasSitemap;
export const OVERFLOW = fasEllipsisH;
export const OVERVIEW = fasThList;
export const PAGE_FIRST = fasFastBackward;
export const PAGE_PREVIOUS = fasBackward;
export const PAGE_NEXT = fasForward;
export const PAGE_LAST = fasFastForward;
export const PARENT = fasLevelUpAlt;
export const PAUSED = fasPause;
export const PENDING = farClock;
export const PROFILE = fasUser;
export const POSTER = fasTh;
export const QUEUED = fasCloud;
export const QUICK = fasRocket;
export const REFRESH = fasSync;
export const REMOVE = fasTimes;
export const RESTART = fasRedoAlt;
export const RESTORE = fasHistory;
export const REORDER = fasBars;
export const RSS = fasRss;
export const SAVE = fasSave;
export const SCHEDULED = farClock;
export const SEARCH = fasSearch;
export const SERIES_CONTINUING = fasPlay;
export const SERIES_ENDED = fasStop;
export const SETTINGS = fasCogs;
export const SHUTDOWN = fasPowerOff;
export const SORT = fasSort;
export const SORT_ASCENDING = fasSortUp;
export const SORT_DESCENDING = fasSortDown;
export const SPINNER = fasSpinner;
export const SUBTRACT = fasMinus;
export const SYSTEM = fasLaptop;
export const TAGS = fasTags;
export const TBA = fasQuestionCircle;
export const UNGROUP = farObjectUngroup;
export const UNKNOWN = fasQuestion;
export const UNMONITORED = farBookmark;
export const UPDATE = fasRetweet;
export const UNSAVED_SETTING = farDotCircle;
export const VIEW = fasEye;
export const WARNING = fasExclamationTriangle;
