// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonContainer': string;
  'buttonIcon': string;
  'buttonsContainer': string;
  'recentFoldersContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
