// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'addCard': string;
  'addCardCenter': string;
  'addCardLabel': string;
  'card': string;
  'grid': string;
  'labels': string;
  'name': string;
  'nameContainer': string;
  'overlay': string;
  'rightCluster': string;
  'statusDot': string;
  'statusDotMuted': string;
  'statusLine': string;
  'statusSeparator': string;
  'statusValue': string;
  'truncatedLabel': string;
  'unnamedName': string;
}
export const cssExports: CssExports;
export default cssExports;
