// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkContainer': string;
  'column': string;
  'columnContainer': string;
  'dragHandle': string;
  'hidden': string;
  'isDragging': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
