// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'columns': string;
  'columnsSection': string;
}
export const cssExports: CssExports;
export default cssExports;
