# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Publish Artifact
description: Publishes a build artifact

inputs:
  runtime:
    description: '.net runtime'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.runtime }}
        path: _artifacts/net6.0/${{ inputs.runtime }}/publish/**/*
