// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentBody': string;
  'innerContentBody': string;
  'noScroll': string;
}
export const cssExports: CssExports;
export default cssExports;
