// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'heading': string;
  'meta': string;
  'metaSep': string;
  'right': string;
  'row': string;
  'scope': string;
  'scopeLine': string;
  'subtitle': string;
  'title': string;
  'titleBlock': string;
}
export const cssExports: CssExports;
export default cssExports;
