// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'chipReset': string;
  'chipStrip': string;
  'folder': string;
  'metaStrip': string;
  'poster': string;
  'posterPlaceholder': string;
  'rowLayout': string;
  'seasonFolderGroup': string;
  'seasonFolderLabel': string;
  'selectInput': string;
  'seriesInfo': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
