// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caret': string;
  'chip': string;
  'chipDisabled': string;
  'chipOverride': string;
  'dot': string;
  'label': string;
  'labelOverride': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
