// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attentionDot': string;
  'buttonGroup': string;
  'compactToggle': string;
  'footerContent': string;
  'footerRow': string;
  'footerShell': string;
  'importButton': string;
  'importButtonContainer': string;
  'importError': string;
  'label': string;
  'loadingButton': string;
  'queueStatus': string;
  'readyDot': string;
  'selectAllContainer': string;
  'selectAllInput': string;
  'selectionGroup': string;
  'selectionLabel': string;
  'statusItem': string;
  'stopButton': string;
}
export const cssExports: CssExports;
export default cssExports;
