// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attentionInfo': string;
  'compact': string;
  'folder': string;
  'folderName': string;
  'identity': string;
  'matchAction': string;
  'matchStatus': string;
  'matchStatusStackedHidden': string;
  'needsAttention': string;
  'poster': string;
  'posterPlaceholder': string;
  'rowLayout': string;
  'searching': string;
  'selectContainer': string;
  'selectInput': string;
  'seriesInfo': string;
  'setting': string;
  'settingLabel': string;
  'settingsRow': string;
  'source': string;
  'stacked': string;
  'titleRow': string;
}
export const cssExports: CssExports;
export default cssExports;
