// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'applyButton': string;
  'defaultsBar': string;
  'defaultsContent': string;
  'defaultsHint': string;
  'defaultsIdentity': string;
  'defaultsTitle': string;
  'setting': string;
  'settingLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
