// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonGroup': string;
  'importButton': string;
  'importButtonContainer': string;
  'importError': string;
  'inputContainer': string;
  'label': string;
  'loading': string;
  'loadingButton': string;
  'processingLabel': string;
  'selectAllInput': string;
  'selectionGroup': string;
  'selectionLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
