// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerCell': string;
  'sortIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
