// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'controlsContainer': string;
  'disabledPageButton': string;
  'loading': string;
  'loadingContainer': string;
  'pageLink': string;
  'pageNumber': string;
  'pageSelect': string;
  'pager': string;
  'records': string;
  'recordsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
