// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'horizontalScroll': string;
  'table': string;
  'tableContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
