// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'info': string;
  'label': string;
  'loading': string;
  'message': string;
  'messageContainer': string;
  'space': string;
  'upToDateIcon': string;
  'update': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
