#!/bin/sh
if [ -f /proc/1/comm ] && [ "`cat /proc/1/comm`" = "systemd" ];
then
  rm -f /etc/init.d/sonarr
  systemctl stop sonarr.service
  systemctl disable sonarr.service
else
  if [ -e "/etc/init.d/sonarr" ]; then
    invoke-rc.d sonarr stop || exit $?
  fi
fi
