// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'calendar': string;
  'calendarContent': string;
}
export const cssExports: CssExports;
export default cssExports;
