// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'optional': string;
  'placeholder': string;
}
export const cssExports: CssExports;
export default cssExports;
