// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'error': string;
  'footer': string;
  'item': string;
  'label': string;
}
export const cssExports: CssExports;
export default cssExports;
