// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'commandName': string;
  'userAgent': string;
}
export const cssExports: CssExports;
export default cssExports;
