// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'duration': string;
  'ended': string;
  'queued': string;
  'started': string;
  'trigger': string;
  'triggerContent': string;
}
export const cssExports: CssExports;
export default cssExports;
