// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearButton': string;
  'helpText': string;
  'input': string;
  'inputContainer': string;
  'inputIconContainer': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
