// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'center': string;
  'danger': string;
  'default': string;
  'large': string;
  'left': string;
  'medium': string;
  'primary': string;
  'right': string;
  'small': string;
  'success': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
