// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'clipboardIconContainer': string;
  'showStateIcon': string;
  'stateIconContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
