// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'iconContainer': string;
  'label': string;
  'showIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
