// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButton': string;
  'item': string;
  'items': string;
  'restriction': string;
  'section': string;
  'sectionHeading': string;
}
export const cssExports: CssExports;
export default cssExports;
