// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'key': string;
  'shortcut': string;
}
export const cssExports: CssExports;
export default cssExports;
