// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'donate': string;
  'header': string;
  'logo': string;
  'logoContainer': string;
  'logoLink': string;
  'right': string;
  'sidebarToggleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
