// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'itemIcon': string;
  'menuButton': string;
}
export const cssExports: CssExports;
export default cssExports;
