// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNewSeriesSuggestion': string;
  'container': string;
  'containerOpen': string;
  'highlighted': string;
  'input': string;
  'inputWrapper': string;
  'list': string;
  'listItem': string;
  'loading': string;
  'ripple': string;
  'searchIcon': string;
  'sectionTitle': string;
  'seriesContainer': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
