// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'content': string;
  'continuing': string;
  'controls': string;
  'deleted': string;
  'ended': string;
  'link': string;
  'meta': string;
  'metaSep': string;
  'nextAiring': string;
  'overlayTitle': string;
  'posterContainer': string;
  'status': string;
  'statusLabel': string;
  'tags': string;
  'tagsList': string;
  'title': string;
  'upcoming': string;
}
export const cssExports: CssExports;
export default cssExports;
