// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'container': string;
  'content': string;
  'controls': string;
  'ended': string;
  'link': string;
  'nextAiring': string;
  'overlayTitle': string;
  'posterContainer': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
