// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'extraLarge': string;
  'large': string;
  'medium': string;
  'modal': string;
  'modalBackdrop': string;
  'modalContainer': string;
  'modalOpen': string;
  'modalOpenIOS': string;
  'small': string;
}
export const cssExports: CssExports;
export default cssExports;
