// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'modalContent': string;
}
export const cssExports: CssExports;
export default cssExports;
