// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addImportListExclusion': string;
  'importListExclusionsHeader': string;
  'title': string;
  'tvdbId': string;
}
export const cssExports: CssExports;
export default cssExports;
