// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'banner': string;
  'bannerGrow': string;
  'bannerImage': string;
  'cell': string;
  'certification': string;
  'checkInput': string;
  'episodeCount': string;
  'episodeProgress': string;
  'genres': string;
  'latestSeason': string;
  'link': string;
  'network': string;
  'nextAiring': string;
  'originalLanguage': string;
  'overlayTitle': string;
  'path': string;
  'previousAiring': string;
  'qualityProfileId': string;
  'ratings': string;
  'releaseGroups': string;
  'seasonCount': string;
  'seasonFolder': string;
  'seriesType': string;
  'sizeOnDisk': string;
  'sortTitle': string;
  'status': string;
  'tags': string;
  'useSceneNumbering': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
