// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'row': string;
  'tableScroller': string;
}
export const cssExports: CssExports;
export default cssExports;
