// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'freeSpace': string;
  'link': string;
  'unavailableLabel': string;
  'unavailablePath': string;
  'unmappedFolders': string;
}
export const cssExports: CssExports;
export default cssExports;
