// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'folderIcon': string;
  'free': string;
  'importable': string;
  'info': string;
  'meta': string;
  'metaSep': string;
  'path': string;
  'row': string;
  'unavailable': string;
  'underlay': string;
}
export const cssExports: CssExports;
export default cssExports;
