// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addNotification': string;
  'center': string;
  'notifications': string;
}
export const cssExports: CssExports;
export default cssExports;
