// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'episode': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
