# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Publish Test Artifact
description: Publishes a test artifact

inputs:
  runtime:
    description: '.net runtime'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: tests-${{ inputs.runtime }}
        path: _tests/net6.0/${{ inputs.runtime }}/publish/**/*
