name: Publish Test Artifact
description: Publishes a test artifact

inputs:
  framework:
    description: '.net framework'
    required: true
  runtime:
    description: '.net runtime'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/upload-artifact@v4
      with:
        name: tests-${{ inputs.runtime }}
        path: _tests/${{ inputs.framework }}/${{ inputs.runtime }}/publish/**/*
