// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'left': string;
  'overflowMenuButton': string;
  'overflowMenuItemIcon': string;
  'right': string;
  'section': string;
  'sectionContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
