// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isDisabled': string;
  'label': string;
  'labelContainer': string;
  'toolbarButton': string;
}
export const cssExports: CssExports;
export default cssExports;
