// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconContainer': string;
  'isDisabled': string;
  'isHidden': string;
  'isMobile': string;
  'isSelected': string;
  'option': string;
  'optionCheck': string;
  'optionCheckInput': string;
}
export const cssExports: CssExports;
export default cssExports;
