// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addAddUser': string;
  'addUsers': string;
  'center': string;
}
export const cssExports: CssExports;
export default cssExports;
