// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loading': string;
  'ripple': string;
  'rippleContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
