// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'deleteButtonContainer': string;
  'deleteButtonInfoIcon': string;
  'formGroupWrapper': string;
  'formGroupsContainer': string;
  'formatItemLarge': string;
  'formatItemSmall': string;
  'intro': string;
  'qualitiesColumn': string;
  'section': string;
  'sectionHeading': string;
  'sectionHeadingRow': string;
}
export const cssExports: CssExports;
export default cssExports;
