// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'deleteButtonContainer': string;
  'deleteButtonInfoIcon': string;
  'formGroupWrapper': string;
  'formGroupsContainer': string;
  'formatItemLarge': string;
  'formatItemSmall': string;
}
export const cssExports: CssExports;
export default cssExports;
