// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chips': string;
  'cutoffChip': string;
  'groupCount': string;
  'moreChip': string;
}
export const cssExports: CssExports;
export default cssExports;
