// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caption': string;
  'column': string;
  'failures': string;
  'field': string;
  'grid': string;
  'human': string;
  'sizeInput': string;
  'sizeLimit': string;
  'slider': string;
  'thumb': string;
  'track': string;
  'unit': string;
}
export const cssExports: CssExports;
export default cssExports;
