// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkInput': string;
  'checkInputContainer': string;
  'createGroupButton': string;
  'dragHandle': string;
  'dragIcon': string;
  'isDragging': string;
  'isInGroup': string;
  'isPreview': string;
  'notAllowed': string;
  'qualityName': string;
  'qualityNameContainer': string;
  'qualityProfileItem': string;
}
export const cssExports: CssExports;
export default cssExports;
