// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'editButtonIcon': string;
  'editGroupsButton': string;
  'editSizesButton': string;
  'qualities': string;
}
export const cssExports: CssExports;
export default cssExports;
