// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'headingRow': string;
  'modeCell': string;
  'modeCellActive': string;
  'modeCluster': string;
  'qualities': string;
  'qualitiesSection': string;
}
export const cssExports: CssExports;
export default cssExports;
