// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'formatName': string;
  'formatNameContainer': string;
  'qualityProfileFormatItem': string;
  'qualityProfileFormatItemContainer': string;
  'scoreContainer': string;
  'scoreInput': string;
}
export const cssExports: CssExports;
export default cssExports;
