// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCustomFormatMessage': string;
  'formats': string;
  'headerContainer': string;
  'headerScore': string;
  'headerTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
