// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addQualityProfile': string;
  'center': string;
  'qualityProfiles': string;
}
export const cssExports: CssExports;
export default cssExports;
