// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkInput': string;
  'checkInputContainer': string;
  'deleteGroupButton': string;
  'dragHandle': string;
  'dragIcon': string;
  'editGroups': string;
  'groupQualities': string;
  'isDragging': string;
  'items': string;
  'name': string;
  'nameContainer': string;
  'nameInput': string;
  'notAllowed': string;
  'qualityNameContainer': string;
  'qualityNameLabel': string;
  'qualityProfileItemGroup': string;
  'qualityProfileItemGroupInfo': string;
}
export const cssExports: CssExports;
export default cssExports;
