// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'qualityProfileItemDragSource': string;
  'qualityProfileItemPlaceholder': string;
  'qualityProfileItemPlaceholderAfter': string;
  'qualityProfileItemPlaceholderBefore': string;
}
export const cssExports: CssExports;
export default cssExports;
