// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'chips': string;
  'cutoffChip': string;
  'cutoffName': string;
  'groupCount': string;
  'moreChip': string;
  'name': string;
  'nameContainer': string;
  'overlay': string;
  'qualityProfile': string;
  'rightCluster': string;
  'statusDot': string;
  'statusLine': string;
  'statusSeparator': string;
}
export const cssExports: CssExports;
export default cssExports;
