// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'title': string;
  'tooltipBody': string;
}
export const cssExports: CssExports;
export default cssExports;
