// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'continuing': string;
  'ended': string;
  'footer': string;
  'legendItem': string;
  'legendItemColor': string;
  'missingMonitored': string;
  'missingUnmonitored': string;
  'statistics': string;
}
export const cssExports: CssExports;
export default cssExports;
