// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bar': string;
  'downloaded': string;
  'downloading': string;
  'fullColor': string;
  'icon': string;
  'indicator': string;
  'legendItem': string;
  'missing': string;
  'onAir': string;
  'unaired': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
