// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addDelayProfile': string;
  'column': string;
  'delayProfiles': string;
  'delayProfilesHeader': string;
  'horizontalScroll': string;
  'tags': string;
}
export const cssExports: CssExports;
export default cssExports;
