// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'column': string;
  'delayProfile': string;
  'dragHandle': string;
  'dragIcon': string;
  'editButton': string;
  'isDragging': string;
  'placeholder': string;
  'placeholderAfter': string;
  'placeholderBefore': string;
}
export const cssExports: CssExports;
export default cssExports;
