// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'colActions': string;
  'colDrag': string;
  'colProto': string;
  'colScope': string;
  'colTorrent': string;
  'colUsenet': string;
  'delayList': string;
  'ghostRow': string;
  'headerCell': string;
  'headerRow': string;
}
export const cssExports: CssExports;
export default cssExports;
