// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'anyText': string;
  'colActions': string;
  'colDrag': string;
  'colLabel': string;
  'colProto': string;
  'colScope': string;
  'colTorrent': string;
  'colUsenet': string;
  'delayProfile': string;
  'dragHandle': string;
  'isDefault': string;
  'isDragging': string;
  'overlay': string;
}
export const cssExports: CssExports;
export default cssExports;
