// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'enabled': string;
  'label': string;
  'name': string;
  'releaseProfile': string;
}
export const cssExports: CssExports;
export default cssExports;
