// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'chips': string;
  'chipsClipped': string;
  'name': string;
  'nameContainer': string;
  'releaseProfile': string;
  'rightCluster': string;
  'showAll': string;
  'statusDot': string;
  'statusLine': string;
  'statusSeparator': string;
}
export const cssExports: CssExports;
export default cssExports;
