// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chips': string;
  'chipsClipped': string;
  'label': string;
  'showAll': string;
}
export const cssExports: CssExports;
export default cssExports;
