# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: Set up environment
description: Runs setup actions and installs packages

inputs:
  framework:
    description: '.net framework'
    required: true
  runtime:
    description: '.net runtime'
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        echo "Packaging ${{inputs.framework}} ${{inputs.runtime}}"
      shell: bash