// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'host': string;
  'path': string;
  'remotePathMapping': string;
}
export const cssExports: CssExports;
export default cssExports;
