// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'addRemotePathMapping': string;
  'host': string;
  'path': string;
  'remotePathMappingsHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
