// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cloneButton': string;
  'downloadClient': string;
  'enabled': string;
  'name': string;
  'nameContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
