// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'day': string;
  'dayOfMonth': string;
  'isDifferentMonth': string;
  'isSingleDay': string;
  'isToday': string;
}
export const cssExports: CssExports;
export default cssExports;
