// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'day': string;
  'days': string;
  'forecast': string;
  'month': string;
  'week': string;
}
export const cssExports: CssExports;
export default cssExports;
