// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'labelContainer': string;
  'labelInputContainer': string;
  'rows': string;
}
export const cssExports: CssExports;
export default cssExports;
