// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isLastTag': string;
  'label': string;
  'or': string;
  'tag': string;
}
export const cssExports: CssExports;
export default cssExports;
