// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'addButton': string;
  'container': string;
  'info': string;
  'intro': string;
  'labelIcon': string;
  'modalFooter': string;
  'poster': string;
  'searchLabel': string;
  'searchOption': string;
  'searchOptions': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
