// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'chip': string;
  'chipDot': string;
  'chipDotAiring': string;
  'chipDotEnded': string;
  'chipDotFinished': string;
  'chipDotUpcoming': string;
  'chipExcluded': string;
  'chips': string;
  'content': string;
  'excludedIcon': string;
  'genres': string;
  'icons': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'searchResult': string;
  'searchResultExcluded': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'tvdbLink': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
