// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearLookupButton': string;
  'emptyBody': string;
  'emptyDivider': string;
  'emptyLink': string;
  'emptyNoLibrary': string;
  'emptyState': string;
  'emptyTitle': string;
  'error': string;
  'resultsLabel': string;
  'searchIcon': string;
  'searchInput': string;
  'searchResults': string;
  'searchSticky': string;
  'searchWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
