// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'info': string;
  'labelIcon': string;
  'modalFooter': string;
  'overview': string;
  'poster': string;
  'searchInput': string;
  'searchInputContainer': string;
  'searchLabel': string;
  'searchLabelContainer': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
