// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'content': string;
  'icons': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'searchResult': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'tvdbLink': string;
  'tvdbLinkIcon': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
