// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'card': string;
  'cardHead': string;
  'cardIcon': string;
  'cardSummary': string;
  'cardTitle': string;
  'grid': string;
  'pageSection': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
