// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'definitions': string;
  'header': string;
  'headerQuality': string;
  'headerTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
