// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quality': string;
  'qualityDefinition': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
