// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'definitions': string;
  'header': string;
  'notice': string;
  'quality': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
