// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'megabytesPerMinute': string;
  'quality': string;
  'qualityDefinition': string;
  'sizeInput': string;
  'sizeLimit': string;
  'sizes': string;
  'slider': string;
  'thumb': string;
  'title': string;
  'track': string;
}
export const cssExports: CssExports;
export default cssExports;
