// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'childLink': string;
  'iconContainer': string;
  'isActiveItem': string;
  'isActiveLink': string;
  'isActiveParentLink': string;
  'item': string;
  'link': string;
  'noIcon': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
