// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brandName': string;
  'divider': string;
  'groupLabel': string;
  'logo': string;
  'logoContainer': string;
  'logoLink': string;
  'sidebar': string;
  'sidebarCloseButton': string;
  'sidebarContainer': string;
  'sidebarHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
