// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'backdrop': string;
  'backdropOpen': string;
  'closeButton': string;
  'focusLock': string;
  'logo': string;
  'logoContainer': string;
  'logoLink': string;
  'mobileHeader': string;
  'mobileSidebarContainer': string;
  'mobileTitle': string;
  'sidebar': string;
  'sidebarCloseButton': string;
  'sidebarContainer': string;
  'sidebarContainerClosed': string;
  'sidebarContainerOpen': string;
  'sidebarHeader': string;
  'sidebarOpen': string;
}
export const cssExports: CssExports;
export default cssExports;
