// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'charts': string;
  'chartsContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
