// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'label': string;
  'secondary': string;
  'summary': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
