// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'autoTagging': string;
  'cloneButton': string;
  'formats': string;
  'name': string;
  'nameContainer': string;
  'tooltipLabel': string;
}
export const cssExports: CssExports;
export default cssExports;
