// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addLabel': string;
  'addSpecification': string;
  'autoTaggings': string;
  'center': string;
  'deleteButton': string;
  'fullWidth': string;
  'rightButtons': string;
  'section': string;
  'sectionHeading': string;
}
export const cssExports: CssExports;
export default cssExports;
