name: "API Docs"

on:
  push:
    paths:
      - ".github/workflows/api_docs.yml"
      - "docs.sh"
      - "src/Sonarr.Api.*/**"
      - "src/Sonarr.Http/**"
      - "src/**/*.csproj"
      - "src/*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  api_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        id: setup-dotnet

      - name: Create openapi.json
        run: ./scripts/docs.sh Linux x64

      - name: Upload openapi.json
        uses: actions/upload-artifact@v4
        path: src/Sonarr.Api.V5/openapi.json
        with:
          name: openapi.json
