# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SOLUTION_FILE: src/Sonarr.sln

jobs:
  build_backend:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Setup Environment Variables
      shell: bash
      run: |
        DOTNET_VERSION=$(jq -r '.sdk.version' global.json)
        echo "SDK_PATH=${{ env.DOTNET_ROOT }}/sdk/${DOTNET_VERSION}" >> "$GITHUB_ENV"
    - name: Enable Extra Platforms In SDK
      shell: bash
      run: ./build.sh --enable-extra-platforms-in-sdk
    - name: Build Backend
      shell: bash
      run: ./build.sh --backend --enable-extra-platforms --packages
