# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SONARR_MAJOR_VERSION: 4
  VERSION: 4.0.0

jobs:
  build_backend:
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - name: Setup Environment Variables
      shell: bash
      run: |
        DOTNET_VERSION=$(jq -r '.sdk.version' global.json)
        echo "SDK_PATH=${{ env.DOTNET_ROOT }}/sdk/${DOTNET_VERSION}" >> "$GITHUB_ENV"
        echo "SONARR_VERSION=${{ env.VERSION }}.${{ github.run_number }}" >> "$GITHUB_ENV"

    - name: Enable Extra Platforms In SDK
      shell: bash
      run: ./build.sh --enable-extra-platforms-in-sdk

    - name: Build Backend
      shell: bash
      run: ./build.sh --backend --enable-extra-platforms --packages

    # Test Artifacts

    - name: Publish win-x64 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: win-x64

    - name: Publish win-x86 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: win-x86

    - name: Publish linux-x64 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-x64

    - name: Publish linux-musl-x64 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-musl-x64

    - name: Publish osx-x64 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: osx-x64

    - name: Publish freebsd-x64 Test Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: freebsd-x64

    # Artifacts

    - name: Publish win-x64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: win-x64

    - name: Publish win-x86 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: win-x86

    - name: Publish linux-x64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-x64

    - name: Publish linux-musl-x64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-musl-x64

    - name: Publish linux-arm64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-arm64

    - name: Publish linux-musl-arm64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-musl-arm64

    - name: Publish linux-arm Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: linux-arm

    - name: Publish osx-x64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: osx-x64

    - name: Publish osx-arm64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: osx-arm64

    - name: Publish freebsd-x64 Artifact
      uses: actions/publish-test-artifact@v1
      with:
        runtime: freebsd-x64

    # Distribution Artifact
    
    - name: Publish Distribution Artifact
      uses: actions/upload-artifact@v4
      with:
        name: distribution
        path: distribution/**/*
