name: Deploy

on:
  workflow_call:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
      major_version:
        description: 'Sonarr major version'
        type: string
        required: true
      version:
        description: 'Sonarr version'
        type: string
        required: true

jobs:
  package:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: freebsd
          - os: ubuntu-latest
            platform: linux
          - os: ubuntu-latest
            platform: macos
          - os: windows-latest
            platform: windows

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Package
      uses: ./.github/actions/package
      with:
        framework: ${{ inputs.framework }}
        platform: ${{ matrix.platform }}
        artifact: build_${{ matrix.platform }}
        branch: ${{ inputs.branch }}
        major_version: ${{ inputs.major_version }}
        version: ${{ inputs.version }}
