name: Deploy

on:
  workflow_call:
    inputs:
      framework: 
        description: '.net framework'
        type: string
        required: true
      branch:
        description: 'Git branch used for this build'
        type: string
        required: true
      major_version:
        description: 'Sonarr major version'
        type: string
        required: true
      version:
        description: 'Sonarr version'
        type: string
        required: true

jobs:
  package:
    strategy:
      matrix:
        platform: [freebsd, linux, macos, windows]
        include:
          - platform: freebsd
            os: ubuntu-latest
          - platform: linux
            os: ubuntu-latest
          - platform: macos
            os: ubuntu-latest
          - platform: windows
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Package
      uses: ./.github/actions/package
      with:
        framework: ${{ inputs.framework }}
        platform: ${{ matrix.platform }}
        artifact: build_${{ matrix.platform }}
        branch: ${{ inputs.branch }}
        major_version: ${{ inputs.major_version }}
        version: ${{ inputs.version }}

  release:
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Download release artifacts
      uses: actions/download-artifact@v4
      with:
        path: _artifacts
        pattern: release_*
        merge-multiple: true

    # - name: Create tag
    #   uses: rickstaa/action-create-tag@v1
    #   id: "tag_create"
    #   with:
    #     tag: v${{ inputs.version }}
    #     message: ""

    - uses: ncipollo/release-action@v1
      with:
        artifacts: _artifacts/Sonarr.*
        commit: ${{ github.sha }}
        generateReleaseNotes: true
        name: ${{ inputs.version }}
        prerelease: ${{ inputs.branch != 'main' }}
        tag: v${{ inputs.version }}
