name: Deploy

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  package_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux
        path: _artifacts
