name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    if: github.repository == 'Sonarr/Sonarr'
    steps:
      - uses: actions/labeler@v5
