// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteEpisodeNumber': string;
  'date': string;
  'downloaded': string;
  'downloading': string;
  'episodeSeparator': string;
  'episodeTitle': string;
  'event': string;
  'eventWrapper': string;
  'missing': string;
  'onAir': string;
  'overlay': string;
  'premiere': string;
  'seasonEpisodeNumber': string;
  'seriesTitle': string;
  'statusIcon': string;
  'time': string;
  'underlay': string;
  'unmonitored': string;
}
export const cssExports: CssExports;
export default cssExports;
